# springboot应用名称
spring.application.name=SpringAI
# 热部署
spring.devtools.livereload.enabled=true
#热部署重新加载java下面类文件
spring.devtools.restart.additional-paths=src/main/java
#排除静态文件重新部署
spring.devtools.restart.exclude=static/**
# Ollama 配置
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=deepseek-r1:8b
# 日志
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.ollama=DEBUG
# 日志编码设置
logging.charset.console=UTF-8
logging.charset.file=UTF-8
# OpenAI 配置 
spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
# OPENAI_API_KEY来自 环境变量，这是测试环境
spring.ai.openai.api-key=${OPENAI_API_KEY}
# OpenAI 模型
spring.ai.openai.chat.options.model=qwen-max-latest